# Generated by Django 5.0.3 on 2024-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_users_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_users_status', 'Can block/unblock user')]},
        ),
    ]
